{% macro get_localized_datepart_names(language, datepart) %}
    {{
        return(
            adapter.dispatch("get_localized_datepart_names", "dbt_date")(
                language, datepart
            )
        )
    }}
{% endmacro %}

{% macro default__get_localized_datepart_names(language, datepart) %}
    {% set datepart_names_by_language = {
        "en": {
            "weekdays": {
                "long": {
                    "1": "Monday",
                    "2": "Tuesday",
                    "3": "Wednesday",
                    "4": "Thursday",
                    "5": "Friday",
                    "6": "Saturday",
                    "7": "Sunday",
                },
                "short": {
                    "1": "Mon",
                    "2": "Tue",
                    "3": "Wed",
                    "4": "Thu",
                    "5": "Fri",
                    "6": "Sat",
                    "7": "Sun",
                },
            },
            "months": {
                "1": "January",
                "2": "February",
                "3": "March",
                "4": "April",
                "5": "May",
                "6": "June",
                "7": "July",
                "8": "August",
                "9": "September",
                "10": "October",
                "11": "November",
                "12": "December",
            },
            "seasons": {
                "1": "winter",
                "2": "spring",
                "3": "summer",
                "4": "autumn",
            },
        },
        "nl": {
            "weekdays": {
                "long": {
                    "1": "maandag",
                    "2": "dinsdag",
                    "3": "woensdag",
                    "4": "donderdag",
                    "5": "vrijdag",
                    "6": "zaterdag",
                    "7": "zondag",
                },
                "short": {
                    "1": "ma",
                    "2": "di",
                    "3": "wo",
                    "4": "do",
                    "5": "vr",
                    "6": "za",
                    "7": "zo",
                },
            },
            "months": {
                "1": "januari",
                "2": "februari",
                "3": "maart",
                "4": "april",
                "5": "mei",
                "6": "juni",
                "7": "juli",
                "8": "augustus",
                "9": "september",
                "10": "oktober",
                "11": "november",
                "12": "december",
            },
            "seasons": {
                "1": "winter",
                "2": "lente",
                "3": "zomer",
                "4": "herfst",
            },
        },
        "de": {
            "weekdays": {
                "long": {
                    "1": "Montag",
                    "2": "Dienstag",
                    "3": "Mittwoch",
                    "4": "Donnerstag",
                    "5": "Freitag",
                    "6": "Samstag",
                    "7": "Sonntag",
                },
                "short": {
                    "1": "Mo",
                    "2": "Di",
                    "3": "Mi",
                    "4": "Do",
                    "5": "Fr",
                    "6": "Sa",
                    "7": "So",
                },
            },
            "months": {
                "1": "Januar",
                "2": "Februar",
                "3": "März",
                "4": "April",
                "5": "Mai",
                "6": "Juni",
                "7": "Juli",
                "8": "August",
                "9": "September",
                "10": "Oktober",
                "11": "November",
                "12": "Dezember",
            },
            "seasons": {
                "1": "Winter",
                "2": "Frühling",
                "3": "Sommer",
                "4": "Herbst",
            },
        },
        "fr": {
            "weekdays": {
                "long": {
                    "1": "lundi",
                    "2": "mardi",
                    "3": "mercredi",
                    "4": "jeudi",
                    "5": "vendredi",
                    "6": "samedi",
                    "7": "dimanche",
                },
                "short": {
                    "1": "lun.",
                    "2": "mar.",
                    "3": "mer.",
                    "4": "jeu.",
                    "5": "ven.",
                    "6": "sam.",
                    "7": "dim.",
                },
            },
            "months": {
                "1": "janvier",
                "2": "février",
                "3": "mars",
                "4": "avril",
                "5": "mai",
                "6": "juin",
                "7": "juillet",
                "8": "août",
                "9": "septembre",
                "10": "octobre",
                "11": "novembre",
                "12": "décembre",
            },
            "seasons": {
                "1": "hiver",
                "2": "printemps",
                "3": "été",
                "4": "automne",
            },
        },
        "es": {
            "weekdays": {
                "long": {
                    "1": "lunes",
                    "2": "martes",
                    "3": "miércoles",
                    "4": "jueves",
                    "5": "viernes",
                    "6": "sábado",
                    "7": "domingo",
                },
                "short": {
                    "1": "lun.",
                    "2": "mar.",
                    "3": "mié.",
                    "4": "jue.",
                    "5": "vie.",
                    "6": "sáb.",
                    "7": "dom.",
                },
            },
            "months": {
                "1": "enero",
                "2": "febrero",
                "3": "marzo",
                "4": "abril",
                "5": "mayo",
                "6": "junio",
                "7": "julio",
                "8": "agosto",
                "9": "septiembre",
                "10": "octubre",
                "11": "noviembre",
                "12": "diciembre",
            },
            "seasons": {
                "1": "invierno",
                "2": "primavera",
                "3": "verano",
                "4": "otoño",
            },
        },
        "it": {
            "weekdays": {
                "long": {
                    "1": "lunedì",
                    "2": "martedì",
                    "3": "mercoledì",
                    "4": "giovedì",
                    "5": "venerdì",
                    "6": "sabato",
                    "7": "domenica",
                },
                "short": {
                    "1": "lun",
                    "2": "mar",
                    "3": "mer",
                    "4": "gio",
                    "5": "ven",
                    "6": "sab",
                    "7": "dom",
                },
            },
            "months": {
                "1": "gennaio",
                "2": "febbraio",
                "3": "marzo",
                "4": "aprile",
                "5": "maggio",
                "6": "giugno",
                "7": "luglio",
                "8": "agosto",
                "9": "settembre",
                "10": "ottobre",
                "11": "novembre",
                "12": "dicembre",
            },
            "seasons": {
                "1": "inverno",
                "2": "primavera",
                "3": "estate",
                "4": "autunno",
            },
        },
        "pt": {
            "weekdays": {
                "long": {
                    "1": "segunda-feira",
                    "2": "terça-feira",
                    "3": "quarta-feira",
                    "4": "quinta-feira",
                    "5": "sexta-feira",
                    "6": "sábado",
                    "7": "domingo",
                },
                "short": {
                    "1": "seg.",
                    "2": "ter.",
                    "3": "qua.",
                    "4": "qui.",
                    "5": "sex.",
                    "6": "sáb.",
                    "7": "dom.",
                },
            },
            "months": {
                "1": "janeiro",
                "2": "fevereiro",
                "3": "março",
                "4": "abril",
                "5": "maio",
                "6": "junho",
                "7": "julho",
                "8": "agosto",
                "9": "setembro",
                "10": "outubro",
                "11": "novembro",
                "12": "dezembro",
            },
            "seasons": {
                "1": "inverno",
                "2": "primavera",
                "3": "verão",
                "4": "outono",
            },
        },
    } %}

    {{ return(datepart_names_by_language[language][datepart]) }}

{% endmacro %}
